#ifndef FUNCTION_PROTOTYPES_H
#define FUNCTION_PROTOTYPES_H

void configureMotors();
void attachEncoderInterrupts();
void setMotorRunning(int belt, int dir, int pwm);
void startMotorByRpm(int belt, int dir, float rpm);
void updateMotorPi();
void stopMotorOutput(int belt);
float calibrateRawToActual(float raw);
float tofKalmanFilter(int idx, float measurement);
uint16_t tofOutputDeadband(int idx, uint16_t candidateMm);
uint16_t applyTofFilter(int idx, uint16_t raw);
void commandBoxAdd(bool explicitId);
bool parcelTypeDimensions(int parcelNo, float* longSide, float* shortSide, float* height);
void encB1();
void encB2();
void encB3();
void encB4();
void handleEncoder(uint8_t b);
void readSerialCommand();
void handleCommand(char* line);
void commandSeqAdd(bool explicitId);
void commandAdd(bool explicitPos);
void commandMove();
void commandSet();
void commandRemove();
void startAuto(uint16_t id);
void autoStep();
bool tryMoveTargetBelt(int targetIdx, int targetBelt, int neededGapBelt);
void saveAutoReasonTargetBlocked(int targetBelt, int neededGapBelt, const char* reason);
void printAutoMove(const __FlashStringHelper* label, int belt, int dir, float mm);
void printAutoCompact(int belt);
void printMoveFault(const char* reason, int belt, int dir, float requested, float traveled);
void printAutoLockReport(int targetIdx, int targetBelt, int neededGapBelt);
void printBeltDiag(int belt);
bool tryOutboundCompletion();
bool tryGapCreation(int neededGapBelt, int targetBelt);
bool tryCompact(int neededGapBelt);
bool tryGreedySafeMove(int targetIdx);
bool tryRefugeAction(int targetIdx);
bool tryRefugeDrop(int candidate);
int chooseRefugeCandidate(int targetIdx);
void requestManualRefuge(int candidate);
void completeManualRefuge();
bool targetAtUnloadZone(int idx);
bool transferSensorComplete(int belt, const Box& box);
bool runBeltMm(int belt, int dir, float mm);
void applyBeltMovementToDb(int belt, float signedMm);
void updateForwardTransfers(int belt);
bool beltHasActiveOutboundTransfer(int belt);
float activeOutboundCompletionDistance(int belt);
float safeForwardDistance(int belt, float desired, bool allowHandoff);
bool movingBeltWouldRotateInbound(int belt);
bool topGapReady(int belt);
float topGapDb(int belt);
bool canCompactToFullTopGap(int belt);
void compactBelt(int belt);
float compactTravelToTop(int belt);
void setCompactTopDb(int belt);
float compactTravelToBottom(int belt);
float guaranteedCompactTravel(int belt);
void setCompactBottomDb(int belt);
int sortedBeltIndices(int belt, int* order);
bool targetHasB4BlockerAhead(int targetIdx);
int topB4PackageAheadOfTarget(int targetIdx);
int topPackageOnBelt(int belt);
int bottomPackageOnBelt(int belt);
bool singleBoxDropSafe(int candidate, float travel);
bool beltHasOverhang(int belt);
float beltTotalAxisLength(int belt);
int beltPackageCount(int belt);
float axisLength(int belt, const Box& box);
float crossLength(int belt, const Box& box);
float incomingEntryPosition(int belt, const Box& box);
float appendPosFor(int belt, float longSide, float shortSide);
bool addSequenceBox(uint16_t id, float longSide, float shortSide, float height);
int chooseSequenceBelt(float longSide, float shortSide);
bool sequenceBeltCanAccept(int belt, float longSide, float shortSide);
void rebuildSequenceLayout();
void rebuildSequenceBelt(int belt);
float loadReserveForBelt(int belt);
int sortedBeltIndicesNewestFirst(int belt, int* order);
bool addBox(uint16_t id, int belt, float pos, float longSide, float shortSide, float height);
int activeBoxCount();
int findBox(uint16_t id);
bool removeBoxById(uint16_t id, const char* label);
void clearDb();
void stopAllMotors();
void zeroEncoders();
void setFault(const char* text);
void clearFault();
void initTofSensors();
void readTofSensors();
void tcaSelect(uint8_t channel);
int gapTofIndex(int belt);
int transferTofIndex(int belt);
int nextBelt(int belt);
int prevBelt(int belt);
int beltAfter(int belt, int n);
int beltBefore(int belt, int n);
int beltNoToIndex(int beltNo);
void toUpperInPlace(char* s);
void printHelp();
void printStatus();
void printManualDiag();
void printSensors();
void printDb();

#endif