#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  cat <<'USAGE'
Usage:
  setup_floor_usb_aliases.sh FLOOR1_TTY FLOOR2_TTY

Example:
  ls -l /dev/serial/by-path/
  ./setup_floor_usb_aliases.sh \
    /dev/serial/by-path/platform-...usb-0:1.2:1.0-port0 \
    /dev/serial/by-path/platform-...usb-0:1.3:1.0-port0

This creates:
  /dev/refuge_floor1
  /dev/refuge_floor2

The mapping is based on the physical USB port path. Keep each Arduino plugged
into the same Raspberry Pi / USB hub port after this setup.
USAGE
  exit 2
fi

floor1_tty="$1"
floor2_tty="$2"

read_id_path() {
  local tty="$1"
  if [[ ! -e "$tty" ]]; then
    echo "ERROR: device not found: $tty" >&2
    exit 1
  fi
  udevadm info -q property -n "$tty" | awk -F= '$1 == "ID_PATH" {print $2; found=1} END {exit found ? 0 : 1}'
}

floor1_path="$(read_id_path "$floor1_tty")"
floor2_path="$(read_id_path "$floor2_tty")"

if [[ -z "$floor1_path" || -z "$floor2_path" ]]; then
  echo "ERROR: failed to read ID_PATH from one of the devices" >&2
  exit 1
fi

if [[ "$floor1_path" == "$floor2_path" ]]; then
  echo "ERROR: both devices resolved to the same ID_PATH" >&2
  exit 1
fi

rule_file="/etc/udev/rules.d/99-refuge-floor-arduino.rules"
tmp_file="$(mktemp)"
cat > "$tmp_file" <<EOF
# Refuge floor Arduino aliases.
# Generated by setup_floor_usb_aliases.sh. These are physical USB-port mappings.
SUBSYSTEM=="tty", ENV{ID_PATH}=="$floor1_path", SYMLINK+="refuge_floor1", GROUP="dialout", MODE="0660"
SUBSYSTEM=="tty", ENV{ID_PATH}=="$floor2_path", SYMLINK+="refuge_floor2", GROUP="dialout", MODE="0660"
EOF

echo "Installing udev rules:"
cat "$tmp_file"
sudo install -m 0644 "$tmp_file" "$rule_file"
rm -f "$tmp_file"

sudo udevadm control --reload-rules
sudo udevadm trigger

echo
echo "Done. Unplug/replug both Arduinos, then check:"
echo "  ls -l /dev/refuge_floor* /dev/serial/by-path/"
