function create_parcel_manual_3d_model()
%CREATE_PARCEL_MANUAL_3D_MODEL Build manual command Simulink interface model.

rootDir = fileparts(fileparts(mfilename('fullpath')));
outDir = fullfile(rootDir, 'outputs');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end
addpath(fileparts(mfilename('fullpath')));

model = 'parcel_manual_3d_interface';
outFile = fullfile(outDir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end
if exist(outFile, 'file')
    delete(outFile);
end

new_system(model);
open_system(model);

set_param(model, ...
    'StopTime', 'inf', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.05', ...
    'SaveOutput', 'on', ...
    'SignalLogging', 'on');

add_block('simulink/Sources/Constant', [model '/LoadCommand'], ...
    'Value', '0', 'Position', [60 70 125 100]);
add_block('simulink/Sources/Constant', [model '/UnloadCommand'], ...
    'Value', '0', 'Position', [60 125 125 155]);
add_block('simulink/Sources/Constant', [model '/TargetId'], ...
    'Value', '1', 'Position', [60 180 125 210]);
add_block('simulink/Sources/Constant', [model '/ResetCommand'], ...
    'Value', '0', 'Position', [60 235 125 265]);

add_block('simulink/Signal Routing/Mux', [model '/CommandMux'], ...
    'Inputs', '4', 'Position', [185 85 205 250]);
add_line(model, 'LoadCommand/1', 'CommandMux/1', 'autorouting', 'on');
add_line(model, 'UnloadCommand/1', 'CommandMux/2', 'autorouting', 'on');
add_line(model, 'TargetId/1', 'CommandMux/3', 'autorouting', 'on');
add_line(model, 'ResetCommand/1', 'CommandMux/4', 'autorouting', 'on');

core = [model '/Manual3DCore'];
load_system('simulink');
interpBlocks = find_system('simulink', 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'RegExp', 'on', ...
    'Name', 'Interpreted MATLAB.*Function');
if isempty(interpBlocks)
    error('Could not find the Interpreted MATLAB Function block in the Simulink library.');
end
add_block(interpBlocks{1}, core, ...
    'MATLABFcn', 'parcel_manual_simulink_step', ...
    'OutputDimensions', '9', ...
    'Position', [285 125 470 205]);
add_line(model, 'CommandMux/1', 'Manual3DCore/1', 'autorouting', 'on');

add_block('simulink/Signal Routing/Demux', [model '/StatusDemux'], ...
    'Outputs', '9', 'Position', [535 75 555 255]);
add_line(model, 'Manual3DCore/1', 'StatusDemux/1', 'autorouting', 'on');

names = {'status_code','loaded_count','unloaded_count','active_floor', ...
    'active_belt','target_id','collision','rotation','idle'};
x0 = 660;
y0 = 45;
dy = 42;
for i = 1:numel(names)
    add_block('simulink/Sinks/Display', [model '/' names{i}], ...
        'Position', [x0 y0+(i-1)*dy x0+110 y0+25+(i-1)*dy]);
    add_line(model, sprintf('StatusDemux/%d', i), sprintf('%s/1', names{i}), ...
        'autorouting', 'on');
end

add_block('simulink/Sinks/To Workspace', [model '/manual_status_vector'], ...
    'VariableName', 'manual_status_vector', ...
    'SaveFormat', 'Array', ...
    'Position', [840 145 1000 175]);
add_line(model, 'Manual3DCore/1', 'manual_status_vector/1', 'autorouting', 'on');

annotationText = sprintf([ ...
    'Manual parcel 3D simulation interface\n\n' ...
    'Inputs:\n' ...
    '- LoadCommand: pulse 1 to generate/load one random parcel\n' ...
    '- UnloadCommand: pulse 1 after setting TargetId\n' ...
    '- TargetId: parcel number to unload\n' ...
    '- ResetCommand: pulse 1 to clear all packages\n\n' ...
    'The Interpreted MATLAB Fcn calls parcel_manual_core_step and updates\n' ...
    'the live 3D HMI via parcel_manual_animation_update.\n\n' ...
    'For easier button operation, run open_parcel_manual_3d_sim.m.\n' ...
    'For digital twin work, replace these command constants with real\n' ...
    'camera/YOLO, TOF, encoder, motor, and platform signals.']);
ann = Simulink.Annotation(model, annotationText);
ann.Position = [45 330 620 520];

save_system(model, outFile);
close_system(model, 0);
fprintf('Created %s\n', outFile);
end
