function create_parcel_algorithm_model()
%CREATE_PARCEL_ALGORITHM_MODEL Build a Simulink model for the revised parcel logic.

rootDir = fileparts(fileparts(mfilename('fullpath')));
outDir = fullfile(rootDir, 'outputs');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

model = 'parcel_belt_algorithm_revised';
outFile = fullfile(outDir, [model '.slx']);

if bdIsLoaded(model)
    close_system(model, 0);
end
if exist(outFile, 'file')
    delete(outFile);
end

new_system(model);
open_system(model);

set_param(model, ...
    'StopTime', '1000', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.05', ...
    'SaveOutput', 'on', ...
    'SignalLogging', 'on');

add_block('simulink/Sources/Clock', [model '/Clock'], ...
    'Position', [70 70 100 100]);

core = [model '/ParcelAlgorithmCore'];
add_block('simulink/User-Defined Functions/MATLAB Function', core, ...
    'Position', [190 35 430 435]);

rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', core);
chart.Script = parcelCoreScript();

add_line(model, 'Clock/1', 'ParcelAlgorithmCore/1', 'autorouting', 'on');

outputs = { ...
    'ids', 'floors', 'belts', 'pos', 'x', 'y', 'yaw', ...
    'phase', 'active_floor', 'active_belt', ...
    'collision_violation', 'rotation_violation', 'same_belt_gap_violation', ...
    'status_code', 'target_id', 'target_floor', 'target_belt', ...
    'loaded_count', 'unloaded_count', ...
    'moving_package_id', 'moving_package_floor', 'moving_package_belt', ...
    'box_long', 'box_short', 'box_height', ...
    'dt_encoder_m', 'dt_tof_gap_m', 'dt_tof_empty', 'dt_motor_cmd', ...
    'dt_platform_floor', 'dt_platform_z', ...
    'dt_current_package_id', 'dt_current_box_long', 'dt_current_box_short', 'dt_current_box_height'};

x0 = 560;
y0 = 30;
dy = 48;
for i = 1:numel(outputs)
    name = outputs{i};
    tw = [model '/' name];
    add_block('simulink/Sinks/To Workspace', tw, ...
        'VariableName', name, ...
        'SaveFormat', 'Array', ...
        'Position', [x0 y0 + (i-1)*dy x0+145 y0 + 25 + (i-1)*dy]);
    add_line(model, sprintf('ParcelAlgorithmCore/%d', i), sprintf('%s/1', name), ...
        'autorouting', 'on');
end

add_block('simulink/Sinks/Display', [model '/phase_display'], ...
    'Position', [760 360 850 390]);
add_block('simulink/Sinks/Display', [model '/active_belt_display'], ...
    'Position', [760 410 850 440]);
add_block('simulink/Sinks/Display', [model '/status_code_display'], ...
    'Position', [760 460 850 490]);
add_block('simulink/Sinks/Display', [model '/target_id_display'], ...
    'Position', [760 510 850 540]);
add_block('simulink/Sinks/Display', [model '/target_floor_display'], ...
    'Position', [760 560 850 590]);
add_block('simulink/Sinks/Display', [model '/target_belt_display'], ...
    'Position', [760 610 850 640]);
add_block('simulink/Sinks/Display', [model '/box_ids_display'], ...
    'Position', [930 70 1100 120]);
add_block('simulink/Sinks/Display', [model '/box_floors_display'], ...
    'Position', [930 150 1100 200]);
add_block('simulink/Sinks/Display', [model '/box_belts_display'], ...
    'Position', [930 230 1100 280]);
add_line(model, 'ParcelAlgorithmCore/8', 'phase_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/10', 'active_belt_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/14', 'status_code_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/15', 'target_id_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/16', 'target_floor_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/17', 'target_belt_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/1', 'box_ids_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/2', 'box_floors_display/1', 'autorouting', 'on');
add_line(model, 'ParcelAlgorithmCore/3', 'box_belts_display/1', 'autorouting', 'on');

annotationText = sprintf([ ...
    'Revised parcel belt algorithm core\n' ...
    '- Flow: Belt4 -> Belt1 -> Belt2 -> Belt3 -> Belt4\n' ...
    '- Loading method 2: fill Belt3 first, then Belt2, Belt1, Belt4\n' ...
    '- Exactly one belt command is active at a time\n' ...
    '- Package yaw is fixed; no rotation is commanded\n' ...
    '- Packages follow the inner corner lane; fixed corner gap is TOF-tracked\n' ...
    '- Loading packages can enter with random platform lateral x, then align from Belt1\n' ...
    '- Same-belt compactness is measured; physical corner gaps are allowed\n\n' ...
    'HMI status_code: 1=loading, 2=circulation, 3=unloading, 4=complete\n' ...
    'target_* reports the active loading package or unload target\n' ...
    'box_ids/floors/belts displays provide numeric package labels\n\n' ...
    'Digital twin sensor emulation outputs:\n' ...
    'dt_* vectors use [F1B1 F1B2 F1B3 F1B4 F2B1 ... F3B4]\n' ...
    'Replace dt_* emulation with hardware encoder/TOF/motor/platform signals later.']);
ann = Simulink.Annotation(model, annotationText);
ann.Position = [55 500 760 635];

save_system(model, outFile);
close_system(model, 0);
fprintf('Created %s\n', outFile);
end

function script = parcelCoreScript()
script = [
"function [ids, floors, belts, pos, x, y, yaw, phase, active_floor, active_belt, collision_violation, rotation_violation, same_belt_gap_violation, status_code, target_id_out, target_floor_out, target_belt_out, loaded_count, unloaded_count, moving_package_id, moving_package_floor, moving_package_belt, box_long, box_short, box_height, dt_encoder_m, dt_tof_gap_m, dt_tof_empty, dt_motor_cmd, dt_platform_floor, dt_platform_z, dt_current_package_id, dt_current_box_long, dt_current_box_short, dt_current_box_height] = ParcelAlgorithmCore(t)" newline ...
"% Revised automatic parcel loading/circulation/unloading algorithm." newline ...
"% All state is fixed-size for Simulink code generation." newline ...
"" newline ...
"MAX_PKG = 72;" newline ...
"FLOOR_COUNT = 3;" newline ...
"LOAD_TARGET = 69;" newline ...
"TARGET_COUNT = 3;" newline ...
"Ts = 0.05;" newline ...
"BELT_SPEED = 0.35;      % m/s for normal belt motion" newline ...
"REVERSE_SPEED = 0.25;   % m/s for Belt4 unload reverse/restore" newline ...
"EMPTY_GAP = cornerClearance(); % fixed inner-corner empty zone [m]" newline ...
"UNLOAD_TRAVEL = 0.34;   % Belt4 reverse travel to pull package to platform [m]" newline ...
"TOL = 1.0e-6;" newline ...
"" newline ...
"persistent initialized" newline ...
"persistent pkg_id pkg_floor pkg_belt pkg_pos pkg_long pkg_short pkg_height pkg_active pkg_aligned" newline ...
"persistent mode total_loaded next_unload_index" newline ...
"persistent load_id load_floor load_belt load_long load_short load_height" newline ...
"persistent shift_remaining moving_active moving_belt moving_pos route route_len route_idx" newline ...
"persistent target_ids current_target_id reverse_remaining restore_remaining" newline ...
"persistent belt_encoder" newline ...
"persistent last_t" newline ...
"" newline ...
"if isempty(initialized)" newline ...
"    initialized = true;" newline ...
"    pkg_id = zeros(MAX_PKG,1);" newline ...
"    pkg_floor = zeros(MAX_PKG,1);" newline ...
"    pkg_belt = zeros(MAX_PKG,1);" newline ...
"    pkg_pos = zeros(MAX_PKG,1);" newline ...
"    pkg_long = zeros(MAX_PKG,1);" newline ...
"    pkg_short = zeros(MAX_PKG,1);" newline ...
"    pkg_height = zeros(MAX_PKG,1);" newline ...
"    pkg_active = zeros(MAX_PKG,1);" newline ...
"    pkg_aligned = zeros(MAX_PKG,1);" newline ...
"    mode = 0;" newline ...
"    total_loaded = 0;" newline ...
"    next_unload_index = 1;" newline ...
"    load_id = 0;" newline ...
"    load_floor = 0;" newline ...
"    load_belt = 0;" newline ...
"    load_long = 0;" newline ...
"    load_short = 0;" newline ...
"    load_height = 0;" newline ...
"    shift_remaining = 0;" newline ...
"    moving_active = 0;" newline ...
"    moving_belt = 0;" newline ...
"    moving_pos = 0;" newline ...
"    route = zeros(4,1);" newline ...
"    route_len = 0;" newline ...
"    route_idx = 0;" newline ...
"    target_ids = [3; 2; 1];" newline ...
"    current_target_id = 0;" newline ...
"    reverse_remaining = 0;" newline ...
"    restore_remaining = 0;" newline ...
"    belt_encoder = zeros(12,1);" newline ...
"    last_t = -Ts;" newline ...
"end" newline ...
"" newline ...
"dt = t - last_t;" newline ...
"if dt < Ts * 0.5" newline ...
"    dt = 0;" newline ...
"else" newline ...
"    dt = Ts;" newline ...
"    last_t = t;" newline ...
"end" newline ...
"" newline ...
"active_floor = 0;" newline ...
"active_belt = 0;" newline ...
"encoder_delta = 0;" newline ...
"motor_dir = 0;" newline ...
"" newline ...
"if dt > 0" newline ...
"    step = BELT_SPEED * dt;" newline ...
"    reverse_step = REVERSE_SPEED * dt;" newline ...
"" newline ...
"    if mode == 0" newline ...
"        if total_loaded < LOAD_TARGET" newline ...
"            load_id = total_loaded + 1;" newline ...
"            load_floor = 1 + mod(load_id - 1, FLOOR_COUNT);" newline ...
"            [load_long, load_short, load_height] = packageDims(load_id);" newline ...
"            load_belt = chooseLoadBelt(load_floor, load_long, load_short, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"            if load_belt <= 0" newline ...
"                mode = 3;" newline ...
"            else" newline ...
"                shift_remaining = cornerShiftNeeded(load_floor, load_belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"                mode = 1;" newline ...
"            end" newline ...
"        else" newline ...
"            mode = 3;" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 1" newline ...
"        active_floor = load_floor;" newline ...
"        active_belt = load_belt;" newline ...
"        d = min(step, shift_remaining);" newline ...
"        if d > 0" newline ...
"            [pkg_belt, pkg_pos, pkg_aligned] = moveBeltForward(load_floor, load_belt, d, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, pkg_aligned, MAX_PKG);" newline ...
"            shift_remaining = shift_remaining - d;" newline ...
"            encoder_delta = d;" newline ...
"            motor_dir = 1;" newline ...
"        end" newline ...
"        if shift_remaining <= TOL" newline ...
"            [route, route_len] = buildLoadRoute(load_belt);" newline ...
"            route_idx = 1;" newline ...
"            moving_active = 1;" newline ...
"            moving_belt = route(route_idx);" newline ...
"            moving_pos = 0;" newline ...
"            mode = 2;" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 2" newline ...
"        active_floor = load_floor;" newline ...
"        active_belt = moving_belt;" newline ...
"        d = step;" newline ...
"        moving_pos = moving_pos + d;" newline ...
"        encoder_delta = d;" newline ...
"        motor_dir = 1;" newline ...
"        final_axis = axisLengthForBelt(load_belt, load_long, load_short);" newline ...
"        final_stop = cornerClearance() - final_axis / 2;" newline ...
"        if final_stop < final_axis / 2" newline ...
"            final_stop = final_axis / 2;" newline ...
"        end" newline ...
"        if route_idx == route_len" newline ...
"            if moving_pos >= final_stop" newline ...
"                total_loaded = total_loaded + 1;" newline ...
"                idx = total_loaded;" newline ...
"                pkg_id(idx) = load_id;" newline ...
"                pkg_floor(idx) = load_floor;" newline ...
"                pkg_belt(idx) = load_belt;" newline ...
"                pkg_pos(idx) = final_stop;" newline ...
"                pkg_long(idx) = load_long;" newline ...
"                pkg_short(idx) = load_short;" newline ...
"                pkg_height(idx) = load_height;" newline ...
"                pkg_active(idx) = 1;" newline ...
"                if load_belt ~= 4" newline ...
"                    pkg_aligned(idx) = 1;" newline ...
"                else" newline ...
"                    pkg_aligned(idx) = 0;" newline ...
"                end" newline ...
"                moving_active = 0;" newline ...
"                mode = 0;" newline ...
"            end" newline ...
"        else" newline ...
"            if moving_pos >= beltLength(moving_belt)" newline ...
"                route_idx = route_idx + 1;" newline ...
"                moving_belt = route(route_idx);" newline ...
"                moving_pos = 0;" newline ...
"            end" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 3" newline ...
"        if next_unload_index <= TARGET_COUNT" newline ...
"            current_target_id = target_ids(next_unload_index);" newline ...
"            mode = 4;" newline ...
"        else" newline ...
"            mode = 7;" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 4" newline ...
"        idx = findPackageIndex(current_target_id, pkg_id, pkg_active, MAX_PKG);" newline ...
"        if idx <= 0" newline ...
"            next_unload_index = next_unload_index + 1;" newline ...
"            mode = 3;" newline ...
"        else" newline ...
"            tfloor = pkg_floor(idx);" newline ...
"            tbelt = pkg_belt(idx);" newline ...
"            tlen4 = axisLengthForBelt(4, pkg_long(idx), pkg_short(idx));" newline ...
"            if tbelt == 4 && pkg_pos(idx) + tlen4/2 <= cornerClearance() + TOL" newline ...
"                reverse_remaining = UNLOAD_TRAVEL;" newline ...
"                mode = 5;" newline ...
"            else" newline ...
"                [chosen_belt, d] = chooseSafeCirculationMove(tfloor, tbelt, step, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"                active_floor = tfloor;" newline ...
"                active_belt = chosen_belt;" newline ...
"                if d > 0" newline ...
"                    [pkg_belt, pkg_pos, pkg_aligned] = moveBeltForward(tfloor, chosen_belt, d, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, pkg_aligned, MAX_PKG);" newline ...
"                    encoder_delta = d;" newline ...
"                    motor_dir = 1;" newline ...
"                end" newline ...
"            end" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 5" newline ...
"        idx = findPackageIndex(current_target_id, pkg_id, pkg_active, MAX_PKG);" newline ...
"        if idx <= 0" newline ...
"            mode = 6;" newline ...
"        else" newline ...
"            tfloor = pkg_floor(idx);" newline ...
"            active_floor = tfloor;" newline ...
"            active_belt = 4;" newline ...
"            d = min(reverse_step, reverse_remaining);" newline ...
"            [pkg_pos] = moveBeltSigned(tfloor, 4, -d, pkg_floor, pkg_belt, pkg_pos, pkg_active, MAX_PKG);" newline ...
"            reverse_remaining = reverse_remaining - d;" newline ...
"            encoder_delta = d;" newline ...
"            motor_dir = -1;" newline ...
"            if reverse_remaining <= TOL" newline ...
"                pkg_active(idx) = 0;" newline ...
"                pkg_belt(idx) = 0;" newline ...
"                pkg_pos(idx) = 0;" newline ...
"                pkg_aligned(idx) = 0;" newline ...
"                restore_remaining = UNLOAD_TRAVEL;" newline ...
"                mode = 6;" newline ...
"            end" newline ...
"        end" newline ...
"" newline ...
"    elseif mode == 6" newline ...
"        active_belt = 4;" newline ...
"        d = min(reverse_step, restore_remaining);" newline ...
"        tfloor = targetFloorFromId(current_target_id);" newline ...
"        active_floor = tfloor;" newline ...
"        [pkg_pos] = moveBeltSigned(tfloor, 4, d, pkg_floor, pkg_belt, pkg_pos, pkg_active, MAX_PKG);" newline ...
"        restore_remaining = restore_remaining - d;" newline ...
"        encoder_delta = d;" newline ...
"        motor_dir = 1;" newline ...
"        if restore_remaining <= TOL" newline ...
"            next_unload_index = next_unload_index + 1;" newline ...
"            current_target_id = 0;" newline ...
"            mode = 3;" newline ...
"        end" newline ...
"    end" newline ...
"    if encoder_delta > 0 && active_floor >= 1 && active_floor <= 3 && active_belt >= 1 && active_belt <= 4" newline ...
"        eidx = sensorIndex(active_floor, active_belt);" newline ...
"        belt_encoder(eidx) = belt_encoder(eidx) + motor_dir * encoder_delta;" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"ids = pkg_id;" newline ...
"floors = pkg_floor;" newline ...
"belts = pkg_belt;" newline ...
"pos = pkg_pos;" newline ...
"box_long = pkg_long;" newline ...
"box_short = pkg_short;" newline ...
"box_height = pkg_height;" newline ...
"x = zeros(MAX_PKG,1);" newline ...
"y = zeros(MAX_PKG,1);" newline ...
"yaw = zeros(MAX_PKG,1);" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5" newline ...
"        [x(i), y(i)] = beltXY(pkg_floor(i), pkg_belt(i), pkg_pos(i), pkg_long(i), pkg_short(i), pkg_id(i), pkg_aligned(i));" newline ...
"        yaw(i) = pi/2;" newline ...
"    else" newline ...
"        x(i) = 0;" newline ...
"        y(i) = -10;" newline ...
"        yaw(i) = pi/2;" newline ...
"    end" newline ...
"end" newline ...
"if moving_active > 0.5" newline ...
"    midx = min(total_loaded + 1, MAX_PKG);" newline ...
"    ids(midx) = load_id;" newline ...
"    floors(midx) = load_floor;" newline ...
"    belts(midx) = moving_belt;" newline ...
"    pos(midx) = moving_pos;" newline ...
"    box_long(midx) = load_long;" newline ...
"    box_short(midx) = load_short;" newline ...
"    box_height(midx) = load_height;" newline ...
"    [x(midx), y(midx)] = beltXY(load_floor, moving_belt, moving_pos, load_long, load_short, load_id, moving_belt ~= 4);" newline ...
"    yaw(midx) = pi/2;" newline ...
"end" newline ...
"" newline ...
"phase = mode;" newline ...
"status_code = statusFromMode(mode);" newline ...
"target_id_out = 0;" newline ...
"target_floor_out = 0;" newline ...
"target_belt_out = 0;" newline ...
"moving_package_id = 0;" newline ...
"moving_package_floor = 0;" newline ...
"moving_package_belt = 0;" newline ...
"if mode == 0 || mode == 1 || mode == 2" newline ...
"    target_id_out = load_id;" newline ...
"    target_floor_out = load_floor;" newline ...
"    target_belt_out = load_belt;" newline ...
"    if moving_active > 0.5" newline ...
"        moving_package_id = load_id;" newline ...
"        moving_package_floor = load_floor;" newline ...
"        moving_package_belt = moving_belt;" newline ...
"    end" newline ...
"elseif mode == 3 || mode == 4 || mode == 5 || mode == 6" newline ...
"    target_id_out = current_target_id;" newline ...
"    if current_target_id > 0" newline ...
"        idx_status = findPackageIndex(current_target_id, pkg_id, pkg_active, MAX_PKG);" newline ...
"        if idx_status > 0" newline ...
"            target_floor_out = pkg_floor(idx_status);" newline ...
"            target_belt_out = pkg_belt(idx_status);" newline ...
"        else" newline ...
"            target_floor_out = targetFloorFromId(current_target_id);" newline ...
"            target_belt_out = 4;" newline ...
"        end" newline ...
"        if mode == 5 || mode == 6" newline ...
"            moving_package_id = current_target_id;" newline ...
"            moving_package_floor = target_floor_out;" newline ...
"            moving_package_belt = 4;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"loaded_count = total_loaded;" newline ...
"unloaded_count = next_unload_index - 1;" newline ...
"if unloaded_count < 0" newline ...
"    unloaded_count = 0;" newline ...
"end" newline ...
"collision_violation = detectOverlap(pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"same_belt_gap_violation = detectInternalGap(pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"rotation_violation = 0;" newline ...
"dt_encoder_m = belt_encoder;" newline ...
"[dt_tof_gap_m, dt_tof_empty] = sensorTofState(ids, floors, belts, pos, box_long, box_short, MAX_PKG, EMPTY_GAP);" newline ...
"dt_motor_cmd = zeros(12,1);" newline ...
"if motor_dir ~= 0 && active_floor >= 1 && active_floor <= 3 && active_belt >= 1 && active_belt <= 4" newline ...
"    dt_motor_cmd(sensorIndex(active_floor, active_belt)) = motor_dir;" newline ...
"end" newline ...
"dt_platform_floor = platformFloorForTwin(status_code, active_floor, target_floor_out);" newline ...
"dt_platform_z = floorHeightForTwin(dt_platform_floor);" newline ...
"dt_current_package_id = target_id_out;" newline ...
"dt_current_box_long = 0;" newline ...
"dt_current_box_short = 0;" newline ...
"dt_current_box_height = 0;" newline ...
"if status_code == 1 && load_id > 0" newline ...
"    dt_current_box_long = load_long;" newline ...
"    dt_current_box_short = load_short;" newline ...
"    dt_current_box_height = load_height;" newline ...
"elseif target_id_out > 0" newline ...
"    idx_dt = findPackageIndex(target_id_out, pkg_id, pkg_active, MAX_PKG);" newline ...
"    if idx_dt > 0" newline ...
"        dt_current_box_long = pkg_long(idx_dt);" newline ...
"        dt_current_box_short = pkg_short(idx_dt);" newline ...
"        dt_current_box_height = pkg_height(idx_dt);" newline ...
"    else" newline ...
"        [dt_current_box_long, dt_current_box_short, dt_current_box_height] = packageDims(target_id_out);" newline ...
"    end" newline ...
"end" newline ...
"" newline ...
"end" newline ...
"" newline ...
"function s = statusFromMode(mode)" newline ...
"if mode == 0 || mode == 1 || mode == 2" newline ...
"    s = 1;" newline ...
"elseif mode == 3 || mode == 4" newline ...
"    s = 2;" newline ...
"elseif mode == 5 || mode == 6" newline ...
"    s = 3;" newline ...
"else" newline ...
"    s = 4;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function idx = sensorIndex(floor, belt)" newline ...
"idx = (floor - 1) * 4 + belt;" newline ...
"end" newline ...
"" newline ...
"function [gap_vec, empty_vec] = sensorTofState(ids, floors, belts, pos, box_long, box_short, MAX_PKG, EMPTY_GAP)" newline ...
"gap_vec = zeros(12,1);" newline ...
"empty_vec = zeros(12,1);" newline ...
"for f = 1:3" newline ...
"    for b = 1:4" newline ...
"        gap = beltLength(b);" newline ...
"        for i = 1:MAX_PKG" newline ...
"            if ids(i) > 0 && floors(i) == f && belts(i) == b" newline ...
"                len = axisLengthForBelt(b, box_long(i), box_short(i));" newline ...
"                v = pos(i) - len/2;" newline ...
"                if v < gap" newline ...
"                    gap = v;" newline ...
"                end" newline ...
"            end" newline ...
"        end" newline ...
"        if gap < 0" newline ...
"            gap = 0;" newline ...
"        end" newline ...
"        idx = sensorIndex(f, b);" newline ...
"        gap_vec(idx) = gap;" newline ...
"        if gap >= EMPTY_GAP" newline ...
"            empty_vec(idx) = 1;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function f = platformFloorForTwin(status_code, active_floor, target_floor)" newline ...
"if target_floor >= 1 && target_floor <= 3" newline ...
"    f = target_floor;" newline ...
"elseif active_floor >= 1 && active_floor <= 3" newline ...
"    f = active_floor;" newline ...
"elseif status_code == 4" newline ...
"    f = 1;" newline ...
"else" newline ...
"    f = 1;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function z = floorHeightForTwin(floor)" newline ...
"if floor == 1" newline ...
"    z = 0.00;" newline ...
"elseif floor == 2" newline ...
"    z = 0.27;" newline ...
"else" newline ...
"    z = 0.54;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function [longSide, shortSide, h] = packageDims(id)" newline ...
"scale = 0.5;" newline ...
"k = boxTypeForId(id);" newline ...
"if k == 1" newline ...
"    a = 0.220; b = 0.190; h0 = 0.090;" newline ...
"elseif k == 2" newline ...
"    a = 0.270; b = 0.180; h0 = 0.150;" newline ...
"elseif k == 3" newline ...
"    a = 0.340; b = 0.250; h0 = 0.210;" newline ...
"elseif k == 4" newline ...
"    a = 0.410; b = 0.310; h0 = 0.280;" newline ...
"else" newline ...
"    a = 0.480; b = 0.380; h0 = 0.340;" newline ...
"end" newline ...
"a = a * scale; b = b * scale; h = h0 * scale;" newline ...
"if a >= b" newline ...
"    longSide = a; shortSide = b;" newline ...
"else" newline ...
"    longSide = b; shortSide = a;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function k = boxTypeForId(id)" newline ...
"% Korea Post parcel box type 1~5, pseudo-random but repeatable by package ID." newline ...
"seed = mod(id * 1103515245 + 12345, 2147483647);" newline ...
"k = mod(seed, 5) + 1;" newline ...
"end" newline ...
"" newline ...
"function L = beltLength(belt)" newline ...
"if belt == 1" newline ...
"    L = 0.51;" newline ...
"elseif belt == 2" newline ...
"    L = 1.36;" newline ...
"elseif belt == 3" newline ...
"    L = 0.51;" newline ...
"else" newline ...
"    L = 1.11;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function len = axisLengthForBelt(belt, longSide, shortSide)" newline ...
"if belt == 1 || belt == 3" newline ...
"    len = longSide;" newline ...
"else" newline ...
"    len = shortSide;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function nb = nextBelt(belt)" newline ...
"if belt == 4" newline ...
"    nb = 1;" newline ...
"elseif belt == 1" newline ...
"    nb = 2;" newline ...
"elseif belt == 2" newline ...
"    nb = 3;" newline ...
"else" newline ...
"    nb = 4;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function belt = chooseLoadBelt(floor, longSide, shortSide, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"order = [3; 2; 1; 4];" newline ...
"belt = 0;" newline ...
"for oi = 1:4" newline ...
"    b = order(oi);" newline ...
"    newLen = axisLengthForBelt(b, longSide, shortSide);" newline ...
"    extent = occupiedExtent(floor, b, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"    shift = cornerShiftNeeded(floor, b, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"    if newLen <= cornerClearance() + 1.0e-6 && extent + shift <= beltLength(b)" newline ...
"        belt = b;" newline ...
"        return;" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function ext = occupiedExtent(floor, belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"ext = 0;" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"        v = pkg_pos(i) + len/2;" newline ...
"        if v > ext" newline ...
"            ext = v;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function [belt, dist] = chooseSafeCirculationMove(floor, desired_belt, step, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"order = zeros(4,1);" newline ...
"order(1) = desired_belt;" newline ...
"for i = 2:4" newline ...
"    order(i) = nextBelt(order(i-1));" newline ...
"end" newline ...
"belt = desired_belt;" newline ...
"dist = 0;" newline ...
"for i = 1:4" newline ...
"    b = order(i);" newline ...
"    if beltMoveIsSafe(floor, b, step, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"        belt = b;" newline ...
"        dist = step;" newline ...
"        return;" newline ...
"    end" newline ...
"end" newline ...
"best_margin = 0;" newline ...
"best_belt = desired_belt;" newline ...
"for i = 1:4" newline ...
"    b = order(i);" newline ...
"    margin = beltFrontMargin(floor, b, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"    if margin > best_margin" newline ...
"        best_margin = margin;" newline ...
"        best_belt = b;" newline ...
"    end" newline ...
"end" newline ...
"belt = best_belt;" newline ...
"if best_margin > 1.0e-5" newline ...
"    dist = min(step, best_margin * 0.95);" newline ...
"else" newline ...
"    dist = 0;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function safe = beltMoveIsSafe(floor, belt, dist, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"safe = 1;" newline ...
"L = beltLength(belt);" newline ...
"nb = nextBelt(belt);" newline ...
"gap_next = topGap(floor, nb, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"will_transfer = 0;" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"        new_pos = pkg_pos(i) + dist;" newline ...
"        if new_pos - len/2 >= L - 1.0e-6" newline ...
"            will_transfer = 1;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if will_transfer > 0.5 && gap_next < cornerClearance() - 1.0e-6" newline ...
"    safe = 0;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function margin = beltFrontMargin(floor, belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"margin = beltLength(belt);" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"        v = beltLength(belt) - (pkg_pos(i) - len/2);" newline ...
"        if v < margin" newline ...
"            margin = v;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if margin < 0" newline ...
"    margin = 0;" newline ...
"end" newline ...
"end" newline ...
"function shift = cornerShiftNeeded(floor, belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"gap = topGap(floor, belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG);" newline ...
"shift = cornerClearance() - gap;" newline ...
"if shift < 0" newline ...
"    shift = 0;" newline ...
"end" newline ...
"end" newline ...
"function c = cornerClearance()" newline ...
"c = 0.25;" newline ...
"end" newline ...
"" newline ...
"function gap = topGap(floor, belt, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"gap = beltLength(belt);" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"        v = pkg_pos(i) - len/2;" newline ...
"        if v < gap" newline ...
"            gap = v;" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"if gap < 0" newline ...
"    gap = 0;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function [route, route_len] = buildLoadRoute(target_belt)" newline ...
"route = zeros(4,1);" newline ...
"route(1) = 4;" newline ...
"route_len = 1;" newline ...
"if target_belt == 4" newline ...
"    return;" newline ...
"end" newline ...
"route_len = 2; route(2) = 1;" newline ...
"if target_belt == 1" newline ...
"    return;" newline ...
"end" newline ...
"route_len = 3; route(3) = 2;" newline ...
"if target_belt == 2" newline ...
"    return;" newline ...
"end" newline ...
"route_len = 4; route(4) = 3;" newline ...
"end" newline ...
"" newline ...
"function [pkg_belt, pkg_pos, pkg_aligned] = moveBeltForward(floor, belt, dist, pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, pkg_aligned, MAX_PKG)" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        pkg_pos(i) = pkg_pos(i) + dist;" newline ...
"    end" newline ...
"end" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"        if pkg_pos(i) - len/2 >= beltLength(belt) - 1.0e-6" newline ...
"            nb = nextBelt(belt);" newline ...
"            next_len = axisLengthForBelt(nb, pkg_long(i), pkg_short(i));" newline ...
"            pkg_pos(i) = cornerClearance() - next_len/2;" newline ...
"            if pkg_pos(i) < next_len/2" newline ...
"                pkg_pos(i) = next_len/2;" newline ...
"            end" newline ...
"            pkg_belt(i) = nb;" newline ...
"            if nb == 1" newline ...
"                pkg_aligned(i) = 1;" newline ...
"            end" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function pkg_pos = moveBeltSigned(floor, belt, dist, pkg_floor, pkg_belt, pkg_pos, pkg_active, MAX_PKG)" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"        pkg_pos(i) = pkg_pos(i) + dist;" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function idx = findPackageIndex(id, pkg_id, pkg_active, MAX_PKG)" newline ...
"idx = 0;" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) > 0.5 && pkg_id(i) == id" newline ...
"        idx = i;" newline ...
"        return;" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function floor = targetFloorFromId(id)" newline ...
"floor = 1 + mod(id - 1, 3);" newline ...
"end" newline ...
"" newline ...
"function [x, y] = beltXY(floor, belt, s, longSide, shortSide, id, aligned)" newline ...
"belt_width = 0.25;" newline ...
"L1 = 0.51;" newline ...
"L3 = 0.51;" newline ...
"L4 = 1.11;" newline ...
"platform_y = -0.35;" newline ...
"stopper_x = -0.15;" newline ...
"stopper_y = platform_y + 0.30;" newline ...
"A_x = stopper_x - 0.03/2;" newline ...
"A_y = stopper_y;" newline ...
"floor_offset = (floor - 2) * 1.7;" newline ...
"belt3_right_x = A_x;" newline ...
"belt3_left_x = belt3_right_x - L3;" newline ...
"belt3_y = A_y + floor_offset;" newline ...
"belt3_connect_y = belt3_y + belt_width/2;" newline ...
"belt4_left_x = A_x;" newline ...
"belt4_right_x = A_x + belt_width;" newline ...
"belt4_x = (belt4_left_x + belt4_right_x)/2;" newline ...
"belt4_start_y = belt3_connect_y - 0.25;" newline ...
"belt4_end_y = belt3_connect_y + L4;" newline ...
"belt1_right_x = belt4_right_x;" newline ...
"belt1_left_x = belt1_right_x - L1;" newline ...
"belt1_y = belt4_end_y + belt_width/2;" newline ...
"belt2_x = belt1_left_x - belt_width/2;" newline ...
"belt2_top_y = belt1_y + belt_width/2;" newline ...
"belt2_bottom_y = belt3_connect_y;" newline ...
"mirror_center_x = -0.295;" newline ...
"b3_left_m = 2 * mirror_center_x - belt3_right_x;" newline ...
"b3_right_m = 2 * mirror_center_x - belt3_left_x;" newline ...
"b4_left_m = 2 * mirror_center_x - belt4_right_x;" newline ...
"b4_right_m = 2 * mirror_center_x - belt4_left_x;" newline ...
"b1_left_m = 2 * mirror_center_x - belt1_right_x;" newline ...
"b1_right_m = 2 * mirror_center_x - belt1_left_x;" newline ...
"b2_x_m = 2 * mirror_center_x - belt2_x;" newline ...
"b2_left_m = b2_x_m - belt_width/2;" newline ...
"if s < 0" newline ...
"    sc = 0;" newline ...
"elseif s > beltLength(belt)" newline ...
"    sc = beltLength(belt);" newline ...
"else" newline ...
"    sc = s;" newline ...
"end" newline ...
"lane = platformLaneFactor(id);" newline ...
"if belt == 4" newline ...
"    if aligned > 0.5" newline ...
"        x = b4_right_m - longSide/2;" newline ...
"    else" newline ...
"        x = lateralCenter(b4_left_m, b4_right_m, longSide, lane);" newline ...
"    end" newline ...
"    y = belt4_start_y + sc;" newline ...
"elseif belt == 1" newline ...
"    x = b1_left_m + sc;" newline ...
"    if aligned > 0.5" newline ...
"        y = belt1_y - belt_width/2 + shortSide/2;" newline ...
"    else" newline ...
"        y = lateralCenter(belt1_y - belt_width/2, belt1_y + belt_width/2, shortSide, lane);" newline ...
"    end" newline ...
"elseif belt == 2" newline ...
"    if aligned > 0.5" newline ...
"        x = b2_left_m + longSide/2;" newline ...
"    else" newline ...
"        x = lateralCenter(b2_left_m, b2_left_m + belt_width, longSide, lane);" newline ...
"    end" newline ...
"    y = belt2_top_y - sc;" newline ...
"elseif belt == 3" newline ...
"    x = b3_right_m - sc;" newline ...
"    y = belt3_y + belt_width/2 - shortSide/2;" newline ...
"else" newline ...
"    x = 0;" newline ...
"    y = -10;" newline ...
"end" newline ...
"end" newline ...
"function center = lateralCenter(lowEdge, highEdge, crossSize, lane)" newline ...
"lo = lowEdge + crossSize/2;" newline ...
"hi = highEdge - crossSize/2;" newline ...
"if hi < lo" newline ...
"    center = (lowEdge + highEdge) / 2;" newline ...
"else" newline ...
"    center = lo + lane * (hi - lo);" newline ...
"end" newline ...
"end" newline ...
"function r = platformLaneFactor(id)" newline ...
"seed = mod(id * 1664525 + 1013904223, 10000);" newline ...
"r = seed / 9999;" newline ...
"if r < 0.08" newline ...
"    r = 0.08;" newline ...
"elseif r > 0.92" newline ...
"    r = 0.92;" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function flag = detectOverlap(pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"flag = 0;" newline ...
"for i = 1:MAX_PKG" newline ...
"    if pkg_active(i) <= 0.5" newline ...
"        continue;" newline ...
"    end" newline ...
"    for j = i+1:MAX_PKG" newline ...
"        if pkg_active(j) > 0.5 && pkg_floor(i) == pkg_floor(j) && pkg_belt(i) == pkg_belt(j)" newline ...
"            b = pkg_belt(i);" newline ...
"            li = axisLengthForBelt(b, pkg_long(i), pkg_short(i));" newline ...
"            lj = axisLengthForBelt(b, pkg_long(j), pkg_short(j));" newline ...
"            ai = pkg_pos(i) - li/2; bi = pkg_pos(i) + li/2;" newline ...
"            aj = pkg_pos(j) - lj/2; bj = pkg_pos(j) + lj/2;" newline ...
"            if ai < bj - 1.0e-4 && aj < bi - 1.0e-4" newline ...
"                flag = 1;" newline ...
"                return;" newline ...
"            end" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
"" newline ...
"function flag = detectInternalGap(pkg_floor, pkg_belt, pkg_pos, pkg_long, pkg_short, pkg_active, MAX_PKG)" newline ...
"flag = 0;" newline ...
"for floor = 1:3" newline ...
"    for belt = 1:4" newline ...
"        starts = zeros(MAX_PKG,1);" newline ...
"        ends = zeros(MAX_PKG,1);" newline ...
"        n = 0;" newline ...
"        for i = 1:MAX_PKG" newline ...
"            if pkg_active(i) > 0.5 && pkg_floor(i) == floor && pkg_belt(i) == belt" newline ...
"                n = n + 1;" newline ...
"                len = axisLengthForBelt(belt, pkg_long(i), pkg_short(i));" newline ...
"                starts(n) = pkg_pos(i) - len/2;" newline ...
"                ends(n) = pkg_pos(i) + len/2;" newline ...
"            end" newline ...
"        end" newline ...
"        if n > 1" newline ...
"            for a = 1:n-1" newline ...
"                for b = a+1:n" newline ...
"                    if starts(b) < starts(a)" newline ...
"                        ts = starts(a); te = ends(a);" newline ...
"                        starts(a) = starts(b); ends(a) = ends(b);" newline ...
"                        starts(b) = ts; ends(b) = te;" newline ...
"                    end" newline ...
"                end" newline ...
"            end" newline ...
"            for k = 1:n-1" newline ...
"                gap = starts(k+1) - ends(k);" newline ...
"                if gap > 0.025" newline ...
"                    flag = 1;" newline ...
"                    return;" newline ...
"                end" newline ...
"            end" newline ...
"        end" newline ...
"    end" newline ...
"end" newline ...
"end" newline ...
""];
script = char(join(script, ''));
end
