<?xml version="1.0"?>
<package format="3">
  <name>hik_camera</name>
  <version>0.1.0</version>
  <description>Hikrobot MVS camera publisher for ROS 2.</description>
  <maintainer email="suhyeon01004-hongik@users.noreply.github.com">Suhyeon Lee</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>rcl_interfaces</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
